#!/usr/bin/python3
def raise_exception():
    geek = "Geeks"
    num = 4
    print(geek + num + geek)
